---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alexaroku-ingress
  annotations:
#    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /echo/roku
          backend:
            serviceName: alexaroku
            servicePort: 3000
