---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alexaroku-ingress
  annotations:
#    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: alexaroku
            port:
              number: 3000
        path: /echo/roku
        pathType: ImplementationSpecific
